### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/api-gateway#1]
- [ ] Stripe consumption-based billing
 - [ ] Add Auth0 integration
 - [ ] Shard log DOs by colo 
 - [ ] Add performance metrics & headers
